server:
  port: 8081

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      globalCors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - POST
              - GET
              - DELETE
              - OPTIONS
      routes:
        - id: CMS-SERVICE
          uri: lb://CMS-SERVICE
          predicates:
            - Path=/api/v1/cms/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: DMS-SERVICE
          uri: lb://DMS-SERVICE
          predicates:
            - Path=/api/v1/dms/**

        - id: LOS-SERVICE
          uri: lb://LOS-SERVICE
          predicates:
            - Path=/api/v1/los/**


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    ip-address: true